/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/VAmJFBILP86
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Arimo } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Gearoq() {
  return (
    <div className="dark:bg-muted dark:text-foreground bg-black">
      <div className="container mx-auto px-6 md:px-8">
        <header className="py-4 md:py-6">
          <div className="container mx-auto flex items-center justify-between">
            <Link
              href="#"
              className="flex items-center gap-2 text-white hover:opacity-75 transition-opacity"
              prefetch={false}
            >
              <LogInIcon className="h-6 w-6 text-blue-500" />
              <span className="text-lg font-semibold text-white">GEAROQ</span>
            </Link>
            <nav className="hidden md:flex items-center gap-4">
              <Link href="#" className="text-sm font-medium text-white hover:underline" prefetch={false}>
                Services
              </Link>
              <Link href="#" className="text-sm font-medium text-white hover:underline" prefetch={false}>
                Case Studies
              </Link>
              <Link href="#" className="text-sm font-medium text-white hover:underline" prefetch={false}>
                About
              </Link>
              <Link href="#" className="text-sm font-medium text-white hover:underline" prefetch={false}>
                Contact
              </Link>
            </nav>
            <Button className="bg-blue-500 hover:bg-blue-600 text-white">Get a Quote</Button>
          </div>
        </header>
        <main>
          <section className="py-16 md:py-24 flex items-center justify-center">
            <div className="container mx-auto px-8 md:px-12">
              <div className="text-center max-w-3xl mx-auto">
                <h1 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-[#ADD8E6] to-[#1E90FF] bg-clip-text text-transparent mb-4">
                  Unlock the Power of Automation
                </h1>
                <p className="text-lg md:text-xl mb-8 text-white">
                  Our agency specializes in transforming your business through innovative automation solutions.
                </p>
                <Button variant="secondary" className="bg-blue-500 hover:bg-blue-600 text-white">
                  Explore Our Services
                </Button>
              </div>
            </div>
          </section>
          <section className="py-16 md:py-24">
            <div className="container mx-auto">
              <h2 className="text-3xl md:text-4xl font-bold mb-8 text-white">Our Services</h2>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                <div className="bg-[#333] p-6 rounded-lg">
                  <WorkflowIcon className="h-8 w-8 mb-4 text-blue-500" />
                  <h3 className="text-xl font-semibold mb-2 text-white">Process Automation</h3>
                  <p className="text-muted-foreground mb-4 text-white">
                    Streamline your business operations with our advanced process automation solutions.
                  </p>
                  <Button className="bg-blue-500 hover:bg-blue-600 text-white">Learn More</Button>
                </div>
                <div className="bg-[#333] p-6 rounded-lg">
                  <WorkflowIcon className="h-8 w-8 mb-4 text-blue-500" />
                  <h3 className="text-xl font-semibold mb-2 text-white">Workflow Optimization</h3>
                  <p className="text-muted-foreground mb-4 text-white">
                    Optimize your workflows and increase efficiency with our innovative solutions.
                  </p>
                  <Button className="bg-blue-500 hover:bg-blue-600 text-white">Learn More</Button>
                </div>
                <div className="bg-[#333] p-6 rounded-lg">
                  <XIcon className="h-8 w-8 mb-4 text-blue-500" />
                  <h3 className="text-xl font-semibold mb-2 text-white">AI-Powered Solutions</h3>
                  <p className="text-muted-foreground mb-4 text-white">
                    Leverage the power of AI to drive innovation and transformation in your business.
                  </p>
                  <Button className="bg-blue-500 hover:bg-blue-600 text-white">Learn More</Button>
                </div>
              </div>
            </div>
          </section>
          <section className="py-16 md:py-24">
          <div className="container mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold mb-8 text-white">Case Studies</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              <div className="bg-[#333] p-6 rounded-lg">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={225}
                  alt="Case Study 1"
                  className="rounded-lg mb-4 w-full h-auto"
                  style={{ aspectRatio: "400/225", objectFit: "cover" }}
                />
                <WorkflowIcon className="h-8 w-8 mb-4 text-blue-500" />
                <h3 className="text-xl font-semibold mb-2 text-white">Process Automation</h3>
                <p className="text-muted-foreground mb-4 text-white">
                  Streamline your business operations with our advanced process automation solutions.
                </p>
                <Button className="bg-blue-500 hover:bg-blue-600 text-white">Learn More</Button>
              </div>
              <div className="bg-[#333] p-6 rounded-lg">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={225}
                  alt="Case Study 2"
                  className="rounded-lg mb-4 w-full h-auto"
                  style={{ aspectRatio: "400/225", objectFit: "cover" }}
                />
                <WorkflowIcon className="h-8 w-8 mb-4 text-blue-500" />
                <h3 className="text-xl font-semibold mb-2 text-white">Workflow Optimization</h3>
                <p className="text-muted-foreground mb-4 text-white">
                  Optimize your workflows and increase efficiency with our innovative solutions.
                </p>
                <Button className="bg-blue-500 hover:bg-blue-600 text-white">Learn More</Button>
              </div>
              <div className="bg-[#333] p-6 rounded-lg">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={225}
                  alt="Case Study 3"
                  className="rounded-lg mb-4 w-full h-auto"
                  style={{ aspectRatio: "400/225", objectFit: "cover" }}
                />
                <WorkflowIcon className="h-8 w-8 mb-4 text-blue-500" />
                <h3 className="text-xl font-semibold mb-2 text-white">AI-Powered Solutions</h3>
                <p className="text-muted-foreground mb-4 text-white">
                  Leverage the power of AI to drive innovation and transformation in your business.
                </p>
                <Button className="bg-blue-500 hover:bg-blue-600 text-white">Learn More</Button>
              </div>
            </div>
            </div>
          </section>
        </main>
        <footer className="py-8 md:py-12">
          <div className="container mx-auto flex flex-col md:flex-row items-center justify-between">
            <div className="flex items-center gap-2 mb-4 md:mb-0">
              <LogInIcon className="h-6 w-6 text-blue-500" />
              <span className="text-lg font-semibold text-white">Automation Agency</span>
            </div>
            <nav className="flex items-center gap-4">
              <Link href="#" className="text-sm font-medium text-white hover:underline" prefetch={false}>
                Services
              </Link>
              <Link href="#" className="text-sm font-medium text-white hover:underline" prefetch={false}>
                Case Studies
              </Link>
              <Link href="#" className="text-sm font-medium text-white hover:underline" prefetch={false}>
                About
              </Link>
              <Link href="#" className="text-sm font-medium text-white hover:underline" prefetch={false}>
                Contact
              </Link>
            </nav>
          </div>
        </footer>
      </div>
    </div>
  )
}

function LogInIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
      <polyline points="10 17 15 12 10 7" />
      <line x1="15" x2="3" y1="12" y2="12" />
    </svg>
  )
}

function WorkflowIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="8" x="3" y="3" rx="2" />
      <path d="M7 11v4a2 2 0 0 0 2 2h4" />
      <rect width="8" height="8" x="13" y="13" rx="2" />
    </svg>
  )
}

function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}